package.json
src/app/app.module.ts
src/app/common/directives/bg-await-promises.ts
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.html
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts
src/app/issuer/components/badgeclass-edit/badgeclass-edit.component.ts
src/app/issuer/issuer.module.ts
src/breakdown/static/css/re-style.css

Add the autocomplete field and fix an error that resulted of the forking feature (edited badges were interpreted as forked badges).

UI create badge autocomplete tags

---

deploy.sh

Add script to automate deployment

Automate production deployment

---

src/app/app.component.scss
src/app/public/components/about/about.component.css
src/app/public/components/about/about.component.html

This PR fix the missing color issue in `about page`.
The issue occurred  due to replacing blue color with violet in this PR [here]( adjust configuration for purple instead of blue #91 )

replace blue color with violett

---

src/environments/environment.staging.ts

In this PR the purple color is updated in staging .env file. Now the correct color is used in both prod and staging ui versions.

update oeb purble color in staging env. file

---

src/app/common/components/formfield-image.ts

Stop propagation of cancel event on file selection

Canceling the Photo Upload kills the whole Badge creating process #148

---

src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.html

Remove competency level from details view

Competency levels still shown when creating a badge

---

src/app/app.component.ts

Don't merge before Friday some time (ask @zven)!

Permanently disable the curtain

---

src/app/catalog/components/issuer-catalog/issuer-catalog.component.html
src/app/catalog/components/issuer-catalog/issuer-catalog.component.ts

This PR closes this ticket [196](https://github.com/mint-o-badges/badgr-ui/issues/196)

feat: allow members to create badges from institutions list

---

src/styles/oeb/oeb_styles.scss

fix: missing checkbox

---

src/app/signup/components/signup/signup.component.ts

This PR closes this ticket: https://github.com/mint-o-badges/badgr-ui/issues/442

fix: show error msg properly

---

src/app/components/accordion.component.ts

Open ESCO link in new tab. Stop propagation to not open/close accordion on click.

fix: esco link in new tab

---

src/app/issuer/components/badgeclass-issue-bulk-award/badgeclass-issue-bulk-award.component.html
src/app/issuer/components/issuer-list/issuer-list.component.html

fix: safari layout

---

src/index.develop.html
src/index.production.html
src/index.staging.html

Update all index files with the new grid for the header.

fix: update all index files with newgrid

---

src/app/components/oeb-checkbox.component.ts
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.css
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.html

feat: redesign competencies, adjust checkbox for formcontrols

---

src/assets/i18n/de.json

Registration: please add word #579

---

src/app/auth/components/welcome/welcome.component.html
src/app/issuer/components/issuer-list/issuer-list.component.html
src/assets/i18n/de.json

- Changed the beta text to the new one. 
- Added beta information to welcome page
(footer is done in the newsletter PR)

feat: add beta text to welcome, change to new text

---

src/app/common/components/badge-detail/badge-detail.component.html
src/app/common/components/badge-detail/badge-detail.component.ts
src/app/common/components/badge-detail/badge-detail.component.types.ts
src/app/recipient/components/recipient-earned-badge-detail/recipient-earned-badge-detail.component.ts

I assumed this `public/badges/:badgeId` should be shared, correct me if im wrong
closes #807

feat: show share button in backpack / badges

---

src/app/components/spartan/ui-button-helm/src/lib/hlm-button.directive.ts
src/app/issuer/components/issuer-list/issuer-list.component.html
tailwind.config.js

feat: simple myissuerlist cards

---

src/app/common/components/badge-detail/badge-detail.component.ts
src/app/common/dialogs/share-social-dialog/share-social-dialog.component.html
src/app/recipient/components/recipient-earned-badge-detail/recipient-earned-badge-detail.component.ts

* feat: enable share option  in scial media
* fix: add recived badge to linkedin profile
* fix: hide outdated social media sharing options
---------

Release: display LinkedIn share badge to profile again

---

src/app/issuer/components/badgeclass-issue-bulk-award-confirmation/badgeclass-issue-bulk-award-confirmation.component.ts
src/app/issuer/services/badgeinstance-api.service.ts

This reverts commit 8adf4d8bb4c60eba9637397ade4464f2a37948be.

Revert "feat: test celery"

---

src/app/app.component.ts
src/app/common/components/badge-detail/badge-detail.component.html
src/app/common/components/bg-badgecard.ts
src/app/common/components/bg-learningpathcard.ts
src/app/common/components/issuer/oeb-issuer-detail.component.html
src/app/common/components/oeb-issuercard.ts
src/app/components/issuer-card/issuer-card.component.html
src/app/issuer/components/issuer-list/issuer-list.component.html
src/app/profile/components/profile/profile.component.html
src/app/public/components/learningpath/learningpath.component.html
src/index.develop.html
src/index.html
src/index.production.html
src/index.staging.html
src/styles/oeb/oeb_styles.scss

also sets correct language attribute on HTML element
issue #1107

fix: fix line breaks for issuer catalog description and unbreakable edge cases

---

src/app/common/components/badge-detail/badge-detail.component.html
src/app/common/components/bg-badgecard.ts

fixes https://github.com/mint-o-badges/badgr-ui/issues/1107#issuecomment-2758529067

fix: two more problems with long lines

---

src/app/public/components/learningpath/learningpath.component.html

@jona159 Sorry this was my bad. Haven't had prettier installed locally and it somehow slipped through.

Fix prettier issues on dev

---

src/app/common/components/badge-detail/badge-detail.component.html
src/app/common/components/badge-detail/badge-detail.component.types.ts
src/app/components/datatable-issuer-staff-requests.component.ts
src/app/components/dialog.component.ts
src/app/components/oeb-dialog.component.ts
src/app/components/spartan/ui-pagination-helm/src/lib/hlm-pagination-ellipsis.component.ts
src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.ts
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts
src/app/issuer/components/issuer-list/issuer-list.component.html
src/app/issuer/components/issuer-list/issuer-list.component.ts
src/app/issuer/components/issuer-staff/issuer-staff.component.html
src/app/issuer/components/issuer-staff/issuer-staff.component.ts
src/app/issuer/models/issuer.model.ts
src/assets/i18n/de.json
src/assets/i18n/en.json

* fix: dont allow removing all competencies during editing
* fix: ellipsis
* fix: show issuer search at the bottom
* fix: clean search field after requesting membership
* fix: add questionmark and margin
* fix: some dialog styles
* fix: underline support email
* fix: validate empty competencies after steps changed
* feat: add copyable info to public issuer badge detail page
* fix: unused imports
* Revert "fix: dont allow removing all competencies during editing"
This reverts commit feff44af027eb449db855c7b400c7ff14de29388.
* feat: adjust styles, add plugin template
* fix: placeholder
* refactor: run prettier
---------

Fix/staging test findings (#1194)

---

src/app/common/components/issuer/oeb-issuer-detail.component.html
src/app/common/components/issuer/oeb-issuer-detail.component.ts
src/app/components/datatable-badges.component.ts
src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.ts
src/app/issuer/components/edit-qr-form/edit-qr-form.component.html
src/app/issuer/components/edit-qr-form/edit-qr-form.component.ts
src/app/issuer/components/issuer-detail/issuer-detail.component.ts
src/app/issuer/components/qrcode-awards/qrcode-awards.component.html
src/app/issuer/components/qrcode-awards/qrcode-awards.component.ts
src/app/issuer/models/qrcode-api.model.ts
src/assets/i18n/de.json
src/assets/i18n/en.json

frontend side implementation for #1114 
blocked by mint-o-badges/badgr-server#392

feat: emails for qr code badge requests

---

src/app/app.component.ts
src/app/common/dialogs/select-issuer-dialog/select-issuer-dialog.component.ts
src/app/issuer/components/badge-selection-dialog/badge-selection-dialog.component.ts
src/app/issuer/components/issuer-list/issuer-list.component.ts
src/app/issuer/services/issuer-manager.service.spec.ts
src/app/issuer/services/issuer-manager.service.ts
src/app/public/components/badgeclass/badgeclass.component.ts

Moves #1275 to staging
* fix(issuer-manager): extend issuerBySlug to search through all issuers
* refactor(issuer-manager): rename allIssuers$ to myIssuers$

Deploy to Staging

---

.github/workflows/registry-build-publish.yml
src/app/issuer/components/badgeclass-edit-copypermissions/badgeclass-edit-copypermissions.component.html
src/app/issuer/services/issuer-manager.service.ts
src/assets/i18n/de.json
src/assets/i18n/en.json

* fix(translations): missing/ misordered translations
* fix(issuers): get issuers by slug from all and my issuers

Fix/staging issues (#1284)

---

src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts
src/assets/i18n/de.json
src/assets/i18n/en.json

* feat: change label
* fix: change key

feat: change label (#1312)

---

src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.ts

Issue: #1337 
Extremely humbled to get to fix the leet issue.
- added a div to scroll to
- check if need for scroll on view init
- check if need for scroll when task status changes

feat: add scroll to batch awarding when active

---

src/app/common/components/issuer/oeb-issuer-detail.component.ts
src/app/components/datatable-qrcodes.component.ts
src/app/components/spartan/ui-input-helm/src/lib/hlm-input.directive.ts
src/app/components/spartan/ui-switch-helm/src/lib/hlm-switch-thumb.directive.ts
src/app/components/spartan/ui-switch-helm/src/lib/hlm-switch.component.ts
src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.ts
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.html
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts
src/app/issuer/components/qrcode-awards/qrcode-awards.component.html
src/app/issuer/components/qrcode-awards/qrcode-awards.component.ts
src/app/recipient/components/recipient-badge-collection-edit-form/recipient-badge-collection-edit-form.component.html
src/app/recipient/components/recipient-badge-collection-edit-form/recipient-badge-collection-edit-form.component.ts
src/assets/i18n/de.json
src/assets/i18n/en.json

* feat: make input text black
* feat: adjust switch colors
* fix: err msg
* fix: qrcode awarding
* fix: validation

Fix/test findings june4 (#1347)

---

src/app/recipient/components/recipient-badge-collection-detail/recipient-badge-collection-detail.component.ts
src/app/recipient/components/recipient-badge-collection-edit-form/recipient-badge-collection-edit-form.component.ts
src/app/recipient/components/recipient-earned-badge-list/recipient-earned-badge-list.component.ts
src/app/recipient/components/recipient-skill-visualisation/recipient-skill-visualisation.component.html
src/app/recipient/components/recipient-skill-visualisation/recipient-skill-visualisation.component.scss
src/app/recipient/components/recipient-skill-visualisation/recipient-skill-visualisation.component.ts
src/assets/i18n/de.json
src/assets/i18n/en.json

* fix: safari bug, rm position style
* fix: tab name collections
* fix: sort list
* fix: tooltip position on safari

Fix/test findings 2july (#1417)

---

src/app/components/datatable-issuer-detail.component.ts
src/app/components/datatable-qrcodes.component.ts
src/app/issuer/components/qrcode-awards/qrcode-awards.component.ts

* fix(issuer-details): bring back issuedOn date
* fix: colors and missing icon
---------

fix/dev testing (#1444)

---

src/app/catalog/components/learningpath-catalog/learningpath-catalog.component.ts
src/app/common/components/badge-detail/badge-detail.component.ts
src/app/common/components/bg-learningpathcard.ts
src/app/public/components/badgeclass/badgeclass.component.ts
src/app/public/components/learningpath/learningpath.component.ts
src/app/recipient/components/recipient-badge-collection-detail/recipient-badge-collection-detail.component.ts
src/app/recipient/components/recipient-earned-badge-list/recipient-earned-badge-list.component.html
src/app/recipient/components/recipient-earned-badge-list/recipient-earned-badge-list.component.ts

* fix: rm space before comma
* fix: disable download of collection if not published
* feat: adjust calculation for learningpath completion

Fix/test findings july15 (#1457)

---

src/app/issuer/components/learningpath-edit-form/learningpath-edit-form.component.ts

Pick for test findings in #1465

fix: default (#1466)

---

src/app/components/datatable-qrcodes.component.ts

fix: disable award badge button while awarding in progress

---

src/app/recipient/components/recipient-skill-visualisation/recipient-skill-visualisation.component.scss

Haven't tested yet (my local database was broken), but this should do it.

feat: adjust bubble colors according to mockup

---

src/app/recipient/components/recipient-skill-visualisation/recipient-skill-visualisation.component.scss

fix: set future skills outlines to correct colors

---

src/app/common/components/issuer/oeb-issuer-detail.component.html
src/app/components/oeb-button.component.ts
src/app/issuer/components/badgeclass-create/badgeclass-create.component.html
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.html
src/app/issuer/components/badgeclass-select-type/badgeclass-select-type.component.html
src/app/issuer/components/issuer-list/issuer-list.component.html
src/app/issuer/components/learningpath-edit-form/learningpath-edit-form.component.html

Implements #1558 (at least partially?)

feat: add umami events for badge creation

---

src/app/app.component.html
src/app/auth/components/login/login.component.html
src/app/auth/components/login/login.component.ts
src/app/catalog/components/issuer-catalog/issuer-catalog.component.html
src/app/catalog/components/issuer-catalog/issuer-catalog.component.ts
src/app/catalog/components/learningpath-catalog/learningpath-catalog.component.html
src/app/catalog/components/learningpath-catalog/learningpath-catalog.component.ts
src/app/catalog/components/network-catalog/network-catalog.component.html
src/app/catalog/components/network-catalog/network-catalog.component.ts
src/app/common/components/badge-detail/badge-detail.component.html
src/app/components/input.component.ts
src/app/components/oeb-checkbox.component.ts
src/app/components/oeb-header-text.component.ts
src/app/components/oeb-tabs.component.ts
src/app/components/spartan/ui-tabs-helm/src/lib/hlm-tabs-trigger.ts
src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.html
src/app/issuer/components/issuer-create/issuer-create.component.html
src/app/issuer/components/issuer-edit-form/issuer-edit-form.component.html
src/app/issuer/components/issuer-list/issuer-list.component.html
src/app/issuer/components/learningpath-edit-form/learningpath-edit-form.component.html
src/app/profile/components/profile/profile.component.html
src/app/profile/components/profile/profile.component.ts
src/app/showcase/components/oeb-showcase.component.html
src/app/signup/components/signup/signup.component.html
src/app/signup/components/signup/signup.component.ts
src/assets/i18n/de.json
src/assets/i18n/en.json
src/main.ts

Fixes #1620 
- Introduced new oeb-header-text component to streamline the look everywhere

fix: style issues
