- angular.json
- src/app/common/components/formfield-markdown.css
- widgets-webpack.config.ts
The main changes necessary were to add semicolons to the imported style sheet and to move the ngx-markdown-editor style import to the angular.json file (as also suggested
[here](https://www.npmjs.com/package/ngx-markdown-editor#usage)), since it's not exported by the package.
> ui: Badge creation criteria glitches

- src/app/common/components/formfield-image.ts
- src/app/common/dialogs/nounproject-dialog/nounproject-dialog.component.html
- src/app/common/dialogs/nounproject-dialog/nounproject-dialog.component.ts
- src/app/common/model/nounproject.model.ts
Use thenounproject API v2 in ui to reflect changes from the server. This is necessary since v1 is deprecated and not accessible for new users anymore.
> ui: Getting logged out when searching for an image

- .github/workflows/registry-build-publish.yml
- package.json
- src/app/profile/components/app-integrations-list/app-integrations-list.component.spec.ts
- src/app/recipient/components/add-badge-dialog/add-badge-dialog.component.spec.ts
- src/app/recipient/components/recipient-badge-collection-create/recipient-badge-collection-create.component.spec.ts
- src/app/recipient/components/recipient-badge-collection-list/recipient-badge-collection-list.component.spec.ts
- src/app/recipient/components/recipient-earned-badge-list/recipient-earned-badge-list.component.spec.ts
Added run to workflow file to execute the tests. The tests are run headless, thus `npm run test-headless` is called (instead of `npm test` or similar).
Also note that I already merged the branch `ui-fix-translation-test-issues` into this branch, since the newly added action fails otherwise (see [this](https://github.com/mint-o-badges/badgr-ui/pull/10) PR).
> UI: add npm test to GitHub check

- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.component.ts
- src/app/public/components/start/start.component.html
- src/app/public/components/start/start.component.ts
- src/breakdown/static/css/re-style.css
Add a curtain that is enabled by default and covers the whole page, except for the imprint. If the imprint is displayed, there's no curtain, but on all other pages.
The curtain can be disabled by the query parameter `curtainEnabled` (e.g. http://localhost:4200/public/start?curtainEnabled=false). The enabled / disabled state is stored in the local storage, so that the query parameter doesn't have to be persisted.
> UI create curtain

- src/app/app.component.ts
- src/app/signup/components/signup-success/signup-success.component.ts
The error message appeared because `refreshProfile` was called when the loggedIn observable was triggered, which was caused because logout was called even though the user was already logged out on registration. Now logout is still called, but with a parameter to ensure that the observable isn't triggered. Also, `refreshProfile` is only called if the user is actually loggedIn when a change is detected.
> Fix error message on signup

- src/app/issuer/components/issuer-staff-create-dialog/issuer-staff-create-dialog.component.ts
The user interface now shows the error message when you add a user that does not exist.
> show error message if trying to add user that does not exist

- src/app/issuer/components/badgeclass-detail/badgeclass-detail.component.html
Currently the "Basierend auf ->"-LInk is always displayed. WIth this PR it will only be displayed if the badge is based on another badge.
> show based on link only if the badge is based on another badge

- src/app/catalog/components/issuer-catalog/issuer-catalog.component.ts
I could only reproduce the problem in LibreWolf, but this fixes it:
Only access mapObject if not undefined
> In some browsers institutions don't load

- src/app/issuer/components/issuer-staff/issuer-staff.component.html
This PR fixes the issue of showing wrong staff member role after add/update a staff member.
> #61: show current issuer role

- .github/workflows/registry-build-publish.yml
Only build main images for Staging. I can't test if this actually works until it's merged. This should fix the issue, because otherwise it always tries to build an extra image and for tagged versions, there are two tags (the version tag and `latest`), meaning that only the second tag gets the `-Staging` postfix. If only images for `main` are built, as long as images with `main` don't have two tags, this should solve the issue.
> Tagged version is pointing to staging

- src/app/public/components/impressum/impressum.component.html
matrix [...] GmbH & Co. KG is not correct. It needs to be
matrix gGmbH
Rittergut Haus Morp | Düsseldorfer Straße 16 
40699 Erkrath bei Düsseldorf
> update company name in imprint #217

- src/app/common/dialogs/export-pdf-dialog/export-pdf-dialog.component.ts
If the issuer that created a badge has no image, the PDF export fails with the following error:
```js
ERROR Error: Failed to load image
at img.onerror [as __zone_symbol__ON_PROPERTYerror] (export-pdf-dialog.component.ts:147:12)
at Image.wrapFn (zone.umd.js:810:43)
at _ZoneDelegate.invokeTask (zone.umd.js:445:35)
at core.mjs:14506:55
at AsyncStackTaggingZoneSpec.onInvokeTask (core.mjs:14506:36)
at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
at Object.onInvokeTask (core.mjs:14819:33)
at _ZoneDelegate.invokeTask (zone.umd.js:444:64)
at Zone.runTask (zone.umd.js:210:51)
at ZoneTask.invokeTask [as invoke] (zone.umd.js:527:38)
```
> PDF export: Don't fail on missing issuer image

- angular.json
- src/app/app.component.ts
- src/app/public/components/impressum/impressum.component.html
- src/index.production.html
- src/index.staging.html
We no have a self-hosted [umami](https://umami.is) instance at https://umami.opensenselab.org
This PR adds `umami` to all build stages (`development`, `staging` and `production`) and closes #271. I have followed @umut0 suggestion to copy the `index.html` for all stages. Now there are three `index.html` files. They are all the same just differ in the `website-id` for `umami`. 
- `index.html`-> `development` (localhost:4200)
- `index.staging.html` -> `staging`
- `index.production.html` -> `production`
The index files used for the different stages are configure in the `angular.json` configuration.
> ⚠️ Remember to adjust all three index files if you change anything
PS: committing the `websiteIds` should be fine because they are bound to a domain.
> feat(tracking):add umami tracking for all environments

- .github/workflows/registry-build-publish.yml
In order to automatically deploy builds from the release branch, we need builds from the release branch.
This should be all that's necessary to change in the codebase; the rest I need to adjust directly on the production server.
> release from release branch

- src/app/issuer/components/issuer-detail/issuer-detail.component.html
Before the text indicating a non verified issuer was only shown in the compact (mobile?) view. Now it's also displayed in the wider view.
> Also display not verified text in wide view

- src/app/auth/components/login/login.component.html
- src/app/auth/components/login/login.component.ts
The button is disabled and the function returns if the urls matche sthe production url.
Note that we can't be 100% sure that this works until we try it on prod. I have tried it with the localhost url instead though and I'm fairly certain that it *should* work.
> feat: disable OIDC login for prod

- src/index.html
- src/index.production.html
- src/index.staging.html
The removed library was linked to resolve 'marked is not defined' error  when relaoding create-badge page. It's now removed as it raises some concerns about privacy policy.
> feat: remove linked js library

- src/app/issuer/components/badgeclass-edit-form/badgeclass-edit-form.component.ts
The studyload is not calculated correctly with the new hours and minutes field, e.g. when adding 1 hour and 30 minutes it results to 100 hours and 30 minutes
> fix: calculate studyLoad correctly

- src/app/common/services/session.service.ts
This clears the old tokens in localStorage, causing the user to be displayed as logged out.
> fix: logout if old login method

- README.md
Setup the project and noticed the link to the angular commit message guidelines was broken.
This fixes that.
> docs: fix broken link to angular commit message guidelines in readme

- src/app/public/components/learningpath/learningpath.component.html
- src/app/public/components/learningpath/learningpath.component.ts
Two changes here as requested in the issue:
1. The number of completed hours/minutes is now formatted according to the `hourPipe` implementation and thus equal to the total number of hours required for the micro degree
2. When there are many badges in a micro degree, the display of earned badges in the progress now overflows by scrolling horizontally if necessary.
Related issue: #1090
> Fix ui issues in micro degree view (#1090)

- package-lock.json
- package.json
- src/app/issuer/models/issuer.model.ts
- src/app/public/components/badgeclass/badgeclass.component.ts
* fix: dont allow removing all competencies during editing
* fix: update spartan version to fix deselecting in multiselect
* Revert "fix: dont allow removing all competencies during editing"
This reverts commit d83d69ae0f4a9371b803c2a0673bfecb7c3b0e18.
> Fix/multiselect deselect (#1182)

- src/app/issuer/models/issuer-api.model.ts
- src/app/issuer/models/issuer.model.ts
* fix: dont allow removing all competencies during editing
* fix: dont filter issuer staff on the client, use response field instead
* Revert "fix: dont allow removing all competencies during editing"
This reverts commit b70c2eee1b8d3cbec0d7073e17f64bb777a0fbf9.
> Refactor/move issuer owner tos check to server (#1205)

- src/app/app.component.html
- src/app/app.component.ts
This previously led to a 403 response by the api and thus to the interceptor picking it up. I found this during a e2e testing and figured that `showIssuersTab()` was actually fundamentally broken.
> fix: hide my institutions nav option when unverified

- src/app/auth/components/login/login.component.html
- src/app/components/spartan/ui-input-helm/src/lib/hlm-input.directive.ts
- src/app/issuer/components/edit-qr-form/edit-qr-form.component.html
- src/app/issuer/components/learningpath-create-steps/learningpath-details/learningpath-details.component.html
- src/app/issuer/components/learningpath-edit-form/learningpath-edit-form.component.ts
Issue: #1218 
Changes made:
`<oeb-input/>`/`hlmInput` component now turns to the error style when its either invalid and touched or invalid and dirty. This is required for when forms are submitted without the user ever focusing one of the inputs (they become dirty but stay untouched).
Previously they would stay in their regular color instead of being highlighted.
The form in question in the issue is now marked dirty on submit, thus highlighting missing fields as a result of the above change.
I reviewed (hopefully) all other forms to check if this had any unwanted side effects, which it didn't. It actually applies the effect correctly to other forms now as well.
Two forms showed one highlighted field on page load. Those turned out to have two components with `[autofocus]="true"`, which …
> feat: highlight invalid untouched inputs when submitting a form

- src/app/common/components/badge-detail/badge-detail.component.html
- src/app/common/components/issuer/oeb-issuer-detail.component.html
- src/app/common/components/oeb-issuercard.ts
- src/app/components/issuer-card/issuer-card.component.html
- src/app/issuer/components/issuer-list/issuer-list.component.html
Issue: #1203 
This ensures all img tags that display issuer images do use `aspect-ratio: 1/1` leading to a square image no matter what.
Non-square images (which are actually not allowed but do exist historically) will get scaled down.
> fix(layout): enforce squareness on issuer images
